### ISSUE TITLE
Support custom `defines` for unittest definitions

### ISSUE THREAD

**Issue by hlovdal** [ianfixes/arduino_ci#104]
In the platform definitions it is possible to inject custom preprocessor defines to be used, e.g.

```yaml
  leonardo:
    board: ...
    package: ...
    gcc:
      features:
      defines:
        - MY_CUSTOM_DEFINE
      warnings:
      flags:
```

What I am missing is for this to be possible to do for unittest definitions (`UNITTEST_SCHEMA`) in `.arduino-ci.yaml` as well, e.g.

```yaml
unittest:
  libraries:
    - SomeLibrary
  defines:
    - SKIP_LCD_TESTS    # all unit tests
  platforms:
    - uno
        defines:
          - USE_FAKE_KEYBOARD    # only uno unit tests
    - leonardo
```
In addition to `defines` a `compiler_argument` option would be applicable to be able to give arguments like `-g -O0 --coverage --std=c++98 ...`.

Currently I am just adding `ret += [ "-DUNIT_TEST", "-g", "--coverage" ]` in `test_args`, but it would be great to not have to modify arduino_ci.

This would be applicable for `compile` as well.
