### ISSUE TITLE
Improve documentation for platform dependent examples

### ISSUE THREAD

**Issue by PRosenb** [ianfixes/arduino_ci#109]
Thanks for creating this project.

In my library, I have examples for all supported platforms as well as some specific ones only for Arduino Uno or only for ESP32. That's needed to show specific features only available on these platforms.
It would be great to add an option to either exclude examples from compilation or the ability to specify their target platform.
Many thanks for considering something like that.

**Comment by ianfixes** [comment]
That feature [already exists](https://github.com/ianfixes/arduino_ci/blob/master/REFERENCE.md#control-how-examples-are-compiled), but I'll take this as feedback that the documentation needs to be improved.  

TL;DR, you need to add a new file to each of your platform specific example directories called `.arduino-ci.yml`.  It should contain the following:

```yml
# Specify that this example should only be run on the `esp32` platform
compile:
  platforms:
    - esp32 # or "uno", or whatever platform
```

Is there anything I could add or word differently in [the referenec documentation](https://github.com/ianfixes/arduino_ci/blob/master/REFERENCE.md) to make this more evident?
