### ISSUE TITLE
This is the simplest arduino-ci.yml I could get working in a gitlab-ci.yml script

### ISSUE THREAD

**Issue by user-name-is-taken** [ianfixes/arduino_ci#127]
[Link to the arduino-ci.yml](https://gitlab.com/robotics_fun/DC_motors/blob/master/.arduino-ci.yaml). I'm posting this because the example you gave here didn't work for my project and ~I almost posted an issue for [this](https://gitlab.com/robotics_fun/DC_motors/-/jobs/260929416) job's confusing errors.~ see #128

**Comment by ianfixes** [comment]
Hi Michael, I'm sorry to hear that you've encountered these problems.  I'm a bit confused by the two links you've posted, because they appear to be for 2 separate issues.  Is that correct?  

It looks like you're trying to draw attention to this part of the config:

```yaml
  testfiles:
  # THIS IS REQUIRED
    # files matching this glob (executed inside the `test/` directory) will be whitelisted for testing
    select:
      - "*-*.*"
```

Did you find that the `testfiles` section or just the `select` subsection was required?  A link to a failing build would be very helpful for me, but I will take a look.  

Please don't hesitate to open a separate issue for the confusing error message; it's my goal to eliminate such things from this project.
