### ISSUE TITLE
Add Windows & Appveyor CI support

### ISSUE THREAD

**Issue by ianfixes** [ianfixes/arduino_ci#32]
## Issue / Feature Request Summary

It's time to add Windows as a supported OS.  There should be no technical limitation here beyond the difficulty of developing it without a Windows machine (relying instead on Appveyor directly).

At the moment, that failure due to lack of OS support (originally raised by @tomduff) is expressed in this form:
```
C:\User\someone\GitHub\arduino_ci\SampleProjects\DoSomething>bundle exec arduino_ci_remote.rb
Installing library under test... Traceback (most recent call last):
        5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bin/arduino_ci_remote.rb:23:in `<main>'
        4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/bin/arduino_ci_remote.rb:23:in `load'
        3: from C:/User/someone/Documents/GitHub/arduino_ci/exe/arduino_ci_remote.rb:66:in `<top (required)>'
        2: from C:/User/someone/Documents/GitHub/arduino_ci/exe/arduino_ci_remote.rb:58:in `assure'
        1: from C:/User/someone/Documents/GitHub/arduino_ci/exe/arduino_ci_remote.rb:32:in `perform_action'
C:/User/someone/GitHub/arduino_ci/exe/arduino_ci_remote.rb:66:in `block in <top (required)>': undefined method `install_local_library' for nil:NilClass (NoMethodError)
```

**Comment by ifreecarve** [comment]
Installing Arduino on Appveyor: https://thinkognito.wordpress.com/2016/09/22/continuous-integration-fuer-arduino-mit-appveyor/

```yml
version: 1.0.{build}
install:
- ps: >-
    (New-Object Net.WebClient).DownloadFile('http://downloads.arduino.cc/arduino-1.6.11-windows.zip', 'C:\projects\arduino.zip')
    Expand-Archive C:\projects\arduino.zip -dest C:\projects\arduino\

    (New-Object Net.WebClient).DownloadFile('http://downloads.arduino.cc/libraries/NicoHood/HID_Project-2.4.3.zip', 'C:\projects\hidproject.zip')
    Expand-Archive C:\projects\hidproject.zip -dest C:\projects\hidproject\
    Copy-Item 'C:\projects\hidproject\HID_Project-2.4.3' 'C:\projects\arduino\arduino-1.6.11\libraries\HID-Project' -recurse
build_script:
- cmd: >-
    cd C:\projects\arduino\arduino-1.6.11
    arduino_debug.exe --verify --board arduino:avr:leonardo --verbose-build C:\projects\REPOSITORYNAME\PATHTOSKETCH\keyboard_layouts.ino
```

**Comment by ianfixes** [comment]
Counterpoint, use cygwin https://github.com/james-d-mitchell/libsemigroups/blob/master/appveyor.yml

```yml
# set clone depth
clone_depth: 5                  # clone entire repository history if not defined

environment:
  matrix:
    - CYG_ARCH: x86
      CYG_ROOT: C:/cygwin
    - CYG_ARCH: x86_64
      CYG_ROOT: C:/cygwin64

install:
  - '%CYG_ROOT%\setup-%CYG_ARCH%.exe -qnNdO -R %CYG_ROOT% -s http://cygwin.mirror.constant.com -l %CYG_ROOT%/var/cache/setup -P autoconf -P automake -P bison -P libgmp-devel -P gcc-core -P gcc-g++ -P mingw-runtime -P mingw-binutils -P mingw-gcc-core -P mingw-gcc-g++ -P mingw-pthreads -P mingw-w32api -P libtool -P make -P python -P gettext-devel -P gettext -P intltool -P libiconv -P pkg-config -P git -P wget -P curl'

build: off

test_script:
  - '%CYG_ROOT%/bin/bash -lc "g++ --version && cd $APPVEYOR_BUILD_FOLDER && ./autogen.sh && ./configure && make check"'
```

**Comment by ianfixes** [comment]
Also, https://www.appveyor.com/docs/lang/ruby/

```yml
install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
```
