### ISSUE TITLE
TestFiles select/reject is being ignored by unit test runner

### ISSUE THREAD

**Issue by ianfixes** [ianfixes/arduino_ci#82]
## System

- Arduino IDE version: `0.1.16`

## Issue Summary

Despite the config allowing selection/rejection of test files by glob pattern:

```yml
unittest:
  testfiles:
    select:
      - "*-*.*"
    reject:
      - "sam-squamsh.*"
```

The test runner is ignoring these settings.
